name: lint-test-and-deploy
on: push
jobs:
    prepare:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.1.1
          - name: Setup Node.js environment       
            uses: actions/setup-node@v3.8.1
            with:
              node-version: '18'
          - name: Install packages
            run: npm i
          - name: Lint Project
            run: npm run lint
          - name: Test app
            run: npm run test
          - name: Build app
            run: npm run build